### ISSUE TITLE
importlib.metadata.PackageNotFoundError: No package metadata was found for radgraph

### ISSUE THREAD

**Issue by shenshaowei** [Stanford-AIMI/radgraph#6]
when i run：
```
from radgraph import RadGraph, F1RadGraph
radgraph = RadGraph()
annotations = radgraph(["no evidence of acute cardiopulmonary process moderate hiatal hernia"])
```
Traceback (most recent call last):
  File "/data108/user_hzx/SSW/NLG/radgraph/test.py", line 8, in <module>
    from radgraph import F1RadGraph
  File "/data108/user_hzx/SSW/NLG/radgraph/radgraph/__init__.py", line 1, in <module>
    from .radgraph import RadGraph
  File "/data108/user_hzx/SSW/NLG/radgraph/radgraph/radgraph.py", line 41, in <module>
    version = importlib.metadata.version('radgraph')
  File "/data108/user_hzx/anaconda3/envs/radgraph/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/data108/user_hzx/anaconda3/envs/radgraph/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/data108/user_hzx/anaconda3/envs/radgraph/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for radgraph
(radgraph) user_hzx@user:~/SSW/NLG/radgraph$ python test.py 
Traceback (most recent call last):
  File "/data108/user_hzx/SSW/NLG/radgraph/test.py", line 1, in <module>
    from radgraph import RadGraph, F1RadGraph
  File "/data108/user_hzx/SSW/NLG/radgraph/radgraph/__init__.py", line 1, in <module>
    from .radgraph import RadGraph
  File "/data108/user_hzx/SSW/NLG/radgraph/radgraph/radgraph.py", line 41, in <module>
    version = importlib.metadata.version('radgraph')
  File "/data108/user_hzx/anaconda3/envs/radgraph/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/data108/user_hzx/anaconda3/envs/radgraph/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/data108/user_hzx/anaconda3/envs/radgraph/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for radgraph
(radgraph) user_hzx@user:~/SSW/NLG/radgraph$ pip show transformers

**Comment by jbdel** [comment]
clone last commit.
Use python 3.10 max. 
run:` pip install -e. .`

Everything should be ok.
